platform: linux
image_resource:
  type: docker-image
  source:
    repository: yarbelk/androider

inputs:
- name: sandbox-android

run:
  path: ./sandbox-android/ci/test.sh
#  path: ls
#  args: ["-l","sandbox-android"]
