resources:
- name: sandbox-android
  type: git
  source:
    uri: https://github.com/alanyjw/sandbox-android.git
    branch: master
- name: google-android-testing
  type: git
  source:
    uri: https://github.com/alanyjw/basic-sample-espresso-testing.git
    branch: master

jobs:
- name: sandbox-unit-test
  plan:
  - get: sandbox-android
    trigger: true
  - task: test
    tags: [android]
    file: sandbox-android/ci/sandbox-unit-test.yml
- name: android-test
  plan:
  - get: sandbox-android
  - get: google-android-testing
    trigger: true
  - task: assemble-instrumentation
    file: sandbox-android/ci/assemble-instrumentation.yml
  - task: instrument
    tags: [android]
    file: sandbox-android/ci/instrument.yml
